"""Add rest to workoutexercises

Revision ID: 8d3091cea5e9
Revises: d0f57ee73e47
Create Date: 2022-05-27 17:52:53.947486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d3091cea5e9'
down_revision = 'd0f57ee73e47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_exercises', sa.Column('rest', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_exercises', 'rest')
    # ### end Alembic commands ###
